name: Rich Appz
favicon: null
layout_spectrum: 0.74659
typography_spectrum: 0.39898
title: Creativity from an Intuitive Mind
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#aeb3b7'
    - '#334049'
    - '#68757e'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
